version: '3.4'

services:
  db:
    image: mysql:5.7
    restart: always
    container_name: playhits_db
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD="root"
      - MYSQL_USER="root"
      - MYSQL_PASSWORD="root"
      - MYSQL_DATABASE="playhits"
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - playhits_net
  api:
    image: playhits-api:0.1
    container_name: playhits_api
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: playhits
    depends_on:
      - db
    links:
      - "db:mysql"
    ports:
      - 3333:3333
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - playhits_net
volumes:
  my-db:
networks:
  playhits_net:
    external: true
